version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: general-blogs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: